name: Actions workflow

on: push

jobs:
  run-github-Action:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: |
          pwd 
          ls 
      - name: Simple forth.txt file
        id: Txt 
<<<<<<< HEAD
        uses: actions/checkout@v2 
=======
        uses: actions/checkout@v2
>>>>>>> 75f13141b91dda04ad7135978f226dff3fa58f67
        with: 
          Number-of-the-file : Number
      - name: Log time
        run: echo "${{steps.Txt.outputs.time}}"    
